### ISSUE TITLE
多个录音实例同时录音问题

### ISSUE THREAD

**Issue by EternalSoySauce** [shaoshuai904/RecordWav#6]
我的项目中有一个录音页面Activity，还有一个带悬浮窗的Service也有录音功能，两处单独录音均没有问题，但如果同时录音，整个录音文件会变的非常大（正常是100K的录音文件会变成几百M）。求解是什么原因

测试设备：三星S8+，Android 9.0

**Comment by EternalSoySauce** [comment]
试了下系统自带的录音机，确实不允许多处同时录音，需要检测当前是否有其他应用正在录音

**Comment by yxwandroid** [comment]
能否支持map3录制

**Comment by EternalSoySauce** [comment]
Android本身不支持mp3录制，得做格式转换




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wilson"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 上午9:58
收件人: "shaoshuai904/RecordWav"<RecordWav@noreply.github.com&gt;; 
抄送: "zero"<1018717197@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shaoshuai904/RecordWav] 多个录音实例同时录音问题 (#6)




能否支持map3录制

**Comment by yxwandroid** [comment]
哪能做一下格式转换的操作吗  或则我来做然后合并过来

**Comment by EternalSoySauce** [comment]
转换库有很多的，你就在github上搜wav/pcm转换mp3就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wilson"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 上午10:03
收件人: "shaoshuai904/RecordWav"<RecordWav@noreply.github.com&gt;; 
抄送: "zero"<1018717197@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shaoshuai904/RecordWav] 多个录音实例同时录音问题 (#6)




哪能做一下格式转换的操作吗  或则我来做然后合并过来

**Comment by yxwandroid** [comment]
好的谢谢

**Comment by yxwandroid** [comment]
> 我的项目中有一个录音页面Activity，还有一个带悬浮窗的Service也有录音功能，两处单独录音均没有问题，但如果同时录音，整个录音文件会变的非常大（正常是100K的录音文件会变成几百M）。求解是什么原因
> 
> 测试设备：三星S8+，Android 9.0
这个插件不支持同时多个录音的
